name: 'SFTP uploader w/options'
color: 'green'
icon: 'upload'
description: 'upload files to server via SFTP'
inputs:
  host:
    required: true
  port:
    required: false
    default: 22
  username:
    required: false
    default: 'root'
  password:
    required: true
  localDir:
    required: true
  remoteDir:
    required: true
  dryRun:
    required: false
    default: false
  excludeMode:
    required: false
    default: 'remove'
  forceUpload:
    required: false
    default: false
  exclude:
    required: false
    default: '[]'
runs:
  using: 'node12'
  main: 'dist/index.js'
